package org.hazelcast.demo.nw.data.avro;

import java.util.Date;

/**
 * This class is generated by the PadoGrid Code Generator. You can modify this
 * class as needed. It will not be overwritten when you generate it again later.
 * 
 * @since Thu Jul 09 11:13:59 EDT 2020
 * @author dpark
 * @see <a href=
 *      "https://github.com/padogrid/padogrid">https://github.com/padogrid/padogrid</a>
 */
public class Order extends org.hazelcast.demo.nw.data.avro.generated.__Order {
	public Order() {
		super();
	}

	public void setOrderDate(Date date) {
		super.setOrderDateLong(date.getTime());
	}

	public Date getOrderDate() {
		return new Date(super.getOrderDateLong());
	}

	public void setShippedDate(Date date) {
		super.setShippedDateLong(date.getTime());
	}

	public Date getShippedDate() {
		return new Date(super.getShippedDateLong());
	}

	public void setRequiredDate(Date date) {
		super.setRequiredDateLong(date.getTime());
	}

	public Date getRequiredDate() {
		return new Date(super.getRequiredDateLong());
	}
}
