package org.hazelcast.demo.nw.data.avro;

import java.util.Date;

/**
 * This class is generated by the PadoGrid Code Generator. You can modify this
 * class as needed. It will not be overwritten when you generate it again later.
 * 
 * The generated class has been modified to handle Date objects.
 * 
 * @since Thu Jul 09 11:13:59 EDT 2020
 * @author dpark
 * @see <a href=
 *      "https://github.com/padogrid/padogrid">https://github.com/padogrid/padogrid</a>
 */
public class Order extends org.hazelcast.demo.nw.data.avro.generated.__Order {
	public Order() {
		super();
	}

	public void setOrderDateObj(Date date) {
		super.setOrderDate(date.getTime());
	}

	public Date getOrderDateObj() {
		return new Date(super.getOrderDate());
	}

	public void setShippedDateObj(Date date) {
		super.setShippedDate(date.getTime());
	}

	public Date getShippedDateObj() {
		return new Date(super.getShippedDate());
	}

	public void setRequiredDateObj(Date date) {
		super.setRequiredDate(date.getTime());
	}

	public Date getRequiredDateObj() {
		return new Date(super.getRequiredDate());
	}
}
